# Generated by Django 5.2.3 on 2025-06-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('poids', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('journal', models.CharField(max_length=100)),
                ('annee', models.CharField(max_length=4)),
                ('lien', models.URLField(blank=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=100)),
                ('nom_etudiant', models.CharField(max_length=100)),
                ('annee', models.CharField(max_length=10)),
                ('lien', models.URLField(blank=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='page_professeur.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('resume', models.TextField()),
                ('lien', models.URLField(blank=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('nbre_credit', models.IntegerField()),
                ('composite', models.BooleanField(default=False)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='utilisateurs.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='page_professeur.ue'),
        ),
    ]
