# Generated by Django 5.2.3 on 2025-08-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page_professeur', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationue',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='utilisateurs.professeur'),
        ),
        migrations.AddField(
            model_name='article',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur'),
        ),
        migrations.AddField(
            model_name='encadrement',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur'),
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='utilisateurs.etudiant'),
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='page_professeur.evaluation'),
        ),
        migrations.AddField(
            model_name='periodesaisie',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_saisie', to='utilisateurs.responsablesaisienote'),
        ),
        migrations.AddField(
            model_name='projet',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.professeur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='page_professeur.ue'),
        ),
        migrations.AddField(
            model_name='affectationue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='page_professeur.ue'),
        ),
    ]
