# Generated by Django 5.2.3 on 2025-08-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0003_remove_parcours_filiere_filiere_parcours_and_more'),
        ('page_professeur', '0003_alter_evaluation_type_alter_ue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='annee_etude',
            field=models.ManyToManyField(related_name='ues', to='inscription_pedagogique.anneeetude'),
        ),
        migrations.AddField(
            model_name='ue',
            name='filiere',
            field=models.ManyToManyField(related_name='ues', to='inscription_pedagogique.filiere'),
        ),
        migrations.AddField(
            model_name='ue',
            name='parcours',
            field=models.ManyToManyField(related_name='ues', to='inscription_pedagogique.parcours'),
        ),
        migrations.AddField(
            model_name='ue',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='inscription_pedagogique.semestre'),
        ),
    ]
