# Generated by Django 5.2.3 on 2025-08-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0005_alter_anneeetude_semestre_alter_filiere_parcours'),
        ('page_professeur', '0004_ue_annee_etude_ue_filiere_ue_parcours_ue_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='inscription_pedagogique.semestre'),
        ),
    ]
