# Generated by Django 5.2.3 on 2025-09-09 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_professeur', '0005_alter_ue_semestre'),
        ('utilisateurs', '0006_alter_etudiant_num_carte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodesaisie',
            name='active',
        ),
        migrations.AlterField(
            model_name='periodesaisie',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_saisie', to='utilisateurs.responsablesaisienote'),
        ),
    ]
