# Generated by Django 5.2.3 on 2025-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_professeur', '0006_remove_periodesaisie_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodesaisie',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
