# Generated by Django 5.2.3 on 2025-09-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_professeur', '0008_ue_description_ue_lien_cours_ue_lien_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='type',
        ),
        migrations.AddField(
            model_name='recherche',
            name='lien',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='lien',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='encadrement',
            name='lien',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien',
            field=models.URLField(),
        ),
    ]
