# Generated by Django 5.2.3 on 2025-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_professeur', '0009_remove_encadrement_type_remove_recherche_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrement',
            name='type',
            field=models.CharField(default='stage', max_length=50),
            preserve_default=False,
        ),
    ]
