# Generated by Django 5.2.3 on 2025-06-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pseudo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('num_carte', models.CharField(max_length=20)),
                ('photo', models.TextField(blank=True)),
                ('date_naiss', models.DateField()),
                ('lieu_naiss', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('quartier', models.CharField(max_length=100)),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
                ('titre', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.TextField(blank=True)),
                ('code_secret', models.CharField(max_length=50)),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='RespInscription',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='ResponsableSaisieNote',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilisateurs.utilisateur')),
            ],
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('statut', models.CharField(max_length=50)),
                ('navigateur', models.CharField(max_length=200)),
                ('resultat', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to='utilisateurs.utilisateur')),
            ],
        ),
    ]
