# Generated by Django 5.2.3 on 2025-08-11 18:46

import apps.utilisateurs.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', apps.utilisateurs.managers.UtilisateurManager()),
            ],
        ),
    ]
