# Generated by Django 5.2.3 on 2025-08-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
    ]
