# Generated by Django 5.2.3 on 2025-08-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='quartier',
        ),
    ]
