# Generated by Django 5.2.3 on 2025-08-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_auto_20250827_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='autre_prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
