# Generated by Django 5.2.3 on 2025-08-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='quartier',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='autre_prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='num_carte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
