# Generated by Django 5.2.3 on 2025-08-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_etudiant_adresse_remove_etudiant_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=1),
        ),
    ]
