# Generated by Django 5.2.3 on 2025-09-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='num_carte',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
