# Generated by Django 5.2.3 on 2025-06-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.anneeacademique')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('annee_etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.anneeetude')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.etudiant')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('annee_etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.anneeetude')),
                ('annee_univ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.filiere')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.parcours')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.respinscription')),
            ],
        ),
    ]
