# Generated by Django 5.2.3 on 2025-08-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription_pedagogique', '0001_initial'),
        ('page_professeur', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='utilisateurs.etudiant'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription_pedagogique.filiere'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='ues',
            field=models.ManyToManyField(related_name='inscriptions', to='page_professeur.ue'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription_pedagogique.parcours'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='parcours',
            field=models.ManyToManyField(related_name='filieres', to='inscription_pedagogique.parcours'),
        ),
        migrations.AddField(
            model_name='anneeetude',
            name='parcours',
            field=models.ManyToManyField(related_name='annees_etude', to='inscription_pedagogique.parcours'),
        ),
        migrations.AddField(
            model_name='periodeinscription',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_inscription', to='utilisateurs.respinscription'),
        ),
        migrations.AddField(
            model_name='anneeetude',
            name='semestre',
            field=models.ManyToManyField(related_name='annees_etude', to='inscription_pedagogique.semestre'),
        ),
    ]
