# Generated by Django 5.2.3 on 2025-08-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='filiere',
        ),
        migrations.AddField(
            model_name='filiere',
            name='parcours',
            field=models.ManyToManyField(blank=True, related_name='filieres', to='inscription_pedagogique.parcours'),
        ),
        migrations.RemoveField(
            model_name='anneeetude',
            name='parcours',
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('annee_etude', models.ManyToManyField(related_name='semestres', to='inscription_pedagogique.anneeetude')),
            ],
        ),
        migrations.AddField(
            model_name='anneeetude',
            name='parcours',
            field=models.ManyToManyField(related_name='annees_etude', to='inscription_pedagogique.parcours'),
        ),
    ]
