# Generated by Django 5.2.3 on 2025-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0003_remove_parcours_filiere_filiere_parcours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='annee_etude',
        ),
        migrations.AddField(
            model_name='anneeetude',
            name='semestre',
            field=models.ManyToManyField(blank=True, related_name='annees_etude', to='inscription_pedagogique.semestre'),
        ),
    ]
