# Generated by Django 5.2.3 on 2025-08-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0004_remove_semestre_annee_etude_anneeetude_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeetude',
            name='semestre',
            field=models.ManyToManyField(related_name='annees_etude', to='inscription_pedagogique.semestre'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='parcours',
            field=models.ManyToManyField(related_name='filieres', to='inscription_pedagogique.parcours'),
        ),
    ]
